spring:
  application:
    name: AskMyDb

  datasource:
    url: jdbc:postgresql://localhost:5434/askmydb
    username: askmydb
    password: askmydb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        options:
          temperature: 0.1
      embedding:
        model: nomic-embed-text
